//go:build darwin || ios

package mcpserver

import "golang.org/x/sys/unix"

const (
	darwinFIONREAD = 0x4004667f
	bpfFCurrentCPU = 0xffffffff
)

func platformNamedConstants() map[string]uint64 {
	return map[string]uint64{
		"AF_UNSPEC": unix.AF_UNSPEC, "AF_UNIX": unix.AF_UNIX, "AF_LOCAL": unix.AF_LOCAL, "AF_INET": unix.AF_INET, "AF_INET6": unix.AF_INET6,
		"SOCK_STREAM": unix.SOCK_STREAM, "SOCK_DGRAM": unix.SOCK_DGRAM, "SOCK_RAW": unix.SOCK_RAW, "SOCK_SEQPACKET": unix.SOCK_SEQPACKET, "SOCK_NONBLOCK": 0, "SOCK_CLOEXEC": 0,
		"IPPROTO_IP": unix.IPPROTO_IP, "IPPROTO_TCP": unix.IPPROTO_TCP, "IPPROTO_UDP": unix.IPPROTO_UDP, "IPPROTO_ICMP": unix.IPPROTO_ICMP, "IPPROTO_ICMPV6": unix.IPPROTO_ICMPV6,
		"SOL_SOCKET": unix.SOL_SOCKET, "SO_REUSEADDR": unix.SO_REUSEADDR, "SO_REUSEPORT": unix.SO_REUSEPORT, "SO_KEEPALIVE": unix.SO_KEEPALIVE, "SO_BROADCAST": unix.SO_BROADCAST, "SO_ERROR": unix.SO_ERROR, "SO_RCVBUF": unix.SO_RCVBUF, "SO_SNDBUF": unix.SO_SNDBUF, "SCM_RIGHTS": unix.SCM_RIGHTS,
		"F_OK": unix.F_OK, "R_OK": unix.R_OK, "W_OK": unix.W_OK, "X_OK": unix.X_OK,
		"O_RDONLY": unix.O_RDONLY, "O_WRONLY": unix.O_WRONLY, "O_RDWR": unix.O_RDWR, "O_CREATE": unix.O_CREAT, "O_CREAT": unix.O_CREAT, "O_EXCL": unix.O_EXCL, "O_TRUNC": unix.O_TRUNC, "O_APPEND": unix.O_APPEND, "O_NONBLOCK": unix.O_NONBLOCK, "O_CLOEXEC": unix.O_CLOEXEC, "O_DIRECTORY": unix.O_DIRECTORY, "O_NOFOLLOW": unix.O_NOFOLLOW, "O_SYNC": unix.O_SYNC,
		"AT_FDCWD": signedConst(unix.AT_FDCWD), "AT_SYMLINK_NOFOLLOW": unix.AT_SYMLINK_NOFOLLOW, "AT_REMOVEDIR": unix.AT_REMOVEDIR,
		"F_DUPFD": unix.F_DUPFD, "F_DUPFD_CLOEXEC": unix.F_DUPFD_CLOEXEC, "F_GETFD": unix.F_GETFD, "F_SETFD": unix.F_SETFD, "F_GETFL": unix.F_GETFL, "F_SETFL": unix.F_SETFL, "F_GETLK": unix.F_GETLK, "F_SETLK": unix.F_SETLK, "F_SETLKW": unix.F_SETLKW, "F_RDLCK": unix.F_RDLCK, "F_WRLCK": unix.F_WRLCK, "F_UNLCK": unix.F_UNLCK,
		"SEEK_SET": 0, "SEEK_CUR": 1, "SEEK_END": 2, "SEEK_START": 0, "SEEK_CURRENT": 1, "SEEKSTART": 0, "SEEKCURRENT": 1, "SEEKEND": 2,
		"MODE_DIR": uint64(unix.S_IFDIR), "MODE_PERM": 0o777, "MODEDIR": uint64(unix.S_IFDIR), "MODEPERM": 0o777,
		"S_IFIFO": unix.S_IFIFO, "S_IFCHR": unix.S_IFCHR, "S_IFBLK": unix.S_IFBLK, "S_IFREG": unix.S_IFREG, "S_IFSOCK": unix.S_IFSOCK,
		"PROT_NONE": unix.PROT_NONE, "PROT_READ": unix.PROT_READ, "PROT_WRITE": unix.PROT_WRITE, "PROT_EXEC": unix.PROT_EXEC,
		"MAP_SHARED": unix.MAP_SHARED, "MAP_PRIVATE": unix.MAP_PRIVATE, "MAP_ANON": unix.MAP_ANON, "MAP_ANONYMOUS": unix.MAP_ANONYMOUS, "MAP_FIXED": unix.MAP_FIXED,
		"MS_ASYNC": unix.MS_ASYNC, "MS_SYNC": unix.MS_SYNC, "MS_INVALIDATE": unix.MS_INVALIDATE,
		"MADV_NORMAL": unix.MADV_NORMAL, "MADV_RANDOM": unix.MADV_RANDOM, "MADV_SEQUENTIAL": unix.MADV_SEQUENTIAL, "MADV_WILLNEED": unix.MADV_WILLNEED, "MADV_DONTNEED": unix.MADV_DONTNEED,
		"POLLIN": unix.POLLIN, "POLLOUT": unix.POLLOUT, "POLLERR": unix.POLLERR, "POLLHUP": unix.POLLHUP, "POLLNVAL": unix.POLLNVAL,
		"SHUT_RD": unix.SHUT_RD, "SHUT_WR": unix.SHUT_WR, "SHUT_RDWR": unix.SHUT_RDWR,
		"SIGSTOP": uint64(unix.SIGSTOP), "SIGCONT": uint64(unix.SIGCONT), "SIGTERM": uint64(unix.SIGTERM), "SIGKILL": uint64(unix.SIGKILL), "SIGCHLD": uint64(unix.SIGCHLD), "SIGTRAP": uint64(unix.SIGTRAP),
		"WNOHANG": unix.WNOHANG, "WUNTRACED": unix.WUNTRACED, "WCONTINUED": unix.WCONTINUED,
		"RUSAGE_SELF": unix.RUSAGE_SELF, "RUSAGE_CHILDREN": signedConst(unix.RUSAGE_CHILDREN), "RLIMIT_NOFILE": unix.RLIMIT_NOFILE, "RLIMIT_CORE": unix.RLIMIT_CORE, "RLIMIT_CPU": unix.RLIMIT_CPU, "RLIMIT_FSIZE": unix.RLIMIT_FSIZE, "RLIMIT_AS": unix.RLIMIT_AS, "RLIMIT_DATA": unix.RLIMIT_DATA, "RLIMIT_STACK": unix.RLIMIT_STACK, "RLIMIT_MEMLOCK": unix.RLIMIT_MEMLOCK, "RLIMIT_NPROC": unix.RLIMIT_NPROC, "RLIMIT_RSS": unix.RLIMIT_RSS,
		"FIONREAD":     darwinFIONREAD,
		"PRIO_PROCESS": unix.PRIO_PROCESS, "PRIO_PGRP": unix.PRIO_PGRP, "PRIO_USER": unix.PRIO_USER,
		"CLOCK_REALTIME": unix.CLOCK_REALTIME, "CLOCK_MONOTONIC": unix.CLOCK_MONOTONIC, "CLOCK_PROCESS_CPUTIME_ID": unix.CLOCK_PROCESS_CPUTIME_ID, "CLOCK_THREAD_CPUTIME_ID": unix.CLOCK_THREAD_CPUTIME_ID, "CLOCK_MONOTONIC_RAW": unix.CLOCK_MONOTONIC_RAW,
		"LOCK_SH": unix.LOCK_SH, "LOCK_EX": unix.LOCK_EX, "LOCK_NB": unix.LOCK_NB, "LOCK_UN": unix.LOCK_UN,
		"SYS_GETPID": unix.SYS_GETPID, "SYS_SENDMSG": unix.SYS_SENDMSG, "SYS_RECVMSG": unix.SYS_RECVMSG,
	}
}
