//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

var syscallLine = regexp.MustCompile(`(?m)^\s*SYS_([A-Z0-9_]+)\s*=\s*([^\s/]+)`) // values in zsysnum files are integer literals

func main() {
	unixDir, err := xsysUnixDir()
	if err != nil {
		fatal(err)
	}

	files, err := filepath.Glob(filepath.Join(unixDir, "zsysnum_linux_*.go"))
	if err != nil {
		fatal(err)
	}
	if len(files) == 0 {
		fatal(fmt.Errorf("no zsysnum_linux_*.go files found in %s", unixDir))
	}
	sort.Strings(files)

	var out bytes.Buffer
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	out.WriteString("// Source: golang.org/x/sys/unix zsysnum_linux_*.go files.\n\n")
	out.WriteString("package mcpserver\n\n")
	out.WriteString("var linuxSyscallNamesByArch = map[string]map[uint64]string{\n")
	for _, file := range files {
		arch := strings.TrimSuffix(strings.TrimPrefix(filepath.Base(file), "zsysnum_linux_"), ".go")
		entries, err := parseSysnumFile(file)
		if err != nil {
			fatal(err)
		}
		if len(entries) == 0 {
			continue
		}

		fmt.Fprintf(&out, "\t%q: {\n", arch)
		for _, nr := range sortedSyscallNumbers(entries) {
			fmt.Fprintf(&out, "\t\t%d: %q,\n", nr, entries[nr])
		}
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n\n")
	out.WriteString(`func linuxSyscallName(arch string, nr uint64) (string, bool) {
	switch arch {
	case "aarch64":
		arch = "arm64"
	case "x86_64":
		arch = "amd64"
	case "i386", "i486", "i586", "i686":
		arch = "386"
	}
	names, ok := linuxSyscallNamesByArch[arch]
	if !ok {
		return "", false
	}
	name, ok := names[nr]
	return name, ok
}
`)

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fatal(fmt.Errorf("format generated source: %w\n%s", err, out.String()))
	}

	_, generatorFile, _, ok := runtime.Caller(0)
	if !ok {
		fatal(fmt.Errorf("cannot locate generator file"))
	}
	outPath := filepath.Join(filepath.Dir(generatorFile), "syscall_names_linux_generated.go")
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func xsysUnixDir() (string, error) {
	if dir := os.Getenv("X_SYS_UNIX_DIR"); dir != "" {
		return dir, nil
	}
	cmd := exec.Command("go", "list", "-f", "{{.Dir}}", "golang.org/x/sys/unix")
	data, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("locate golang.org/x/sys/unix: %w", err)
	}
	return strings.TrimSpace(string(data)), nil
}

func parseSysnumFile(file string) (map[uint64]string, error) {
	data, err := os.ReadFile(file)
	if err != nil {
		return nil, err
	}

	entries := map[uint64]string{}
	for _, match := range syscallLine.FindAllSubmatch(data, -1) {
		nr, err := strconv.ParseUint(string(match[2]), 0, 64)
		if err != nil {
			return nil, fmt.Errorf("parse syscall number in %s: %w", file, err)
		}
		if _, exists := entries[nr]; exists {
			continue
		}
		entries[nr] = strings.ToLower(string(match[1]))
	}
	return entries, nil
}

func sortedSyscallNumbers(entries map[uint64]string) []uint64 {
	numbers := make([]uint64, 0, len(entries))
	for nr := range entries {
		numbers = append(numbers, nr)
	}
	sort.Slice(numbers, func(i, j int) bool { return numbers[i] < numbers[j] })
	return numbers
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
